09_Django/project3/bookproject/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from .views import SignupView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', SignupView.as_view(), name='signup'),
]

09_Django/project3/bookproject/book/urls.py
from django.urls import path

from . import views 

urlpatterns = [
    path('', views.index_view, name='index'),
    path('book/', views.ListBookView.as_view(), name = 'list-book'),
    path('book/<int:pk>/detail/', views.DetailBookView.as_view(), name = 'detail-book'),
    path('book/create/', views.CreateBookView.as_view(), name = 'create-book'),
    path('book/<int:pk>/delete/', views.DeleteBookView.as_view(), name = 'delete-book'),
    path('book/<int:pk>/update/', views.UpdateBookView.as_view(), name = 'update-book'),
    # path('logout/', views.logout_view, name='logout')
]

09_Django/project3/bookproject/bookproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path("", include('book.urls')),
]

09_Django/project3/bookproject/accounts/models.py
from django.db import models

# Create your models here.

09_Django/project3/bookproject/book/models.py
from django.db import models

# Create your models here.

# class SampleModel (models.Model):
#     title = models.CharField(max_length=100)
#     number = models.IntegerField()

CATEGORY = (('buisiness', 'ビジネス'), ('life', '生活'), ('others', 'その他'))

class Book(models.Model):
    title = models.CharField(max_length=100)
    text = models.TextField()
    category = models.CharField(
        max_length=100,
        choices = CATEGORY
    )
    
    def __str__(self):
        return self.title

09_Django/project3/bookproject/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username',)

09_Django/project3/bookproject/accounts/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.views.generic import CreateView


from .forms import SignupForm

# Create your views here.

class SignupView(CreateView):
    model = User
    form_class = SignupForm
    template_name = 'accounts/signup.html'
    success_url = reverse_lazy('index')

09_Django/project3/bookproject/book/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
# from django.contrib.auth import logout
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView
from .models import Book

# Create your views here.
class ListBookView(LoginRequiredMixin, ListView):
    template_name = 'book/book_list.html'
    model = Book

class DetailBookView(LoginRequiredMixin, DetailView):
    template_name = 'book/book_detail.html'
    model = Book

class CreateBookView(LoginRequiredMixin, CreateView):
    template_name = 'book/book_create.html'
    model = Book
    fields = ('title', 'text', 'category')
    success_url = reverse_lazy('list-book')
    
class DeleteBookView(LoginRequiredMixin, DeleteView):
    template_name = 'book/book_delete.html'
    model = Book
    success_url = reverse_lazy('list-book')
    
class UpdateBookView(LoginRequiredMixin, UpdateView):
    template_name = 'book/book_update.html'
    fields = ('title', 'text', 'category')
    success_url = reverse_lazy('list-book')
    model = Book
    
def index_view(request):
    object_list = Book.objects.order_by('category')
    return render(request, 'book/index.html', {'object_list': object_list})

# def logout_view(request):
#     logout(request)
#     return redirect('index')

09_Django/project3/bookproject/accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block title %}アカウント作成{% endblock title %}
{% block h1 %}アカウント作成{% endblock h1 %}

{% block content %}
    <form class="p-4 m-4 bg-light border border-success" method="post">
        {% csrf_token %}
        <input type="text" name="username" class="form-control my-4" placeholder="User ID">
        <input type="password" name="password1" class="form-control mt-4" placeholder="Password">
        <input type="password" name="password2" class="form-control mt-4" placeholder="Password confimation">
        <small class="mb-2 d-block text-start">Passwordは8文字以上</small>
        
        {% if form.errors %}
            <span class="mb-2 small text-danger d-block text-start">利用できないIDやPasswordの可能性があります。入力を再度ご確認ください。</span>
        {% endif %}
            <button type="submit" class="btn btn-success m-2">アカウント作成</button>
    </form>

{% endblock content %}
    
    

09_Django/project3/bookproject/book/templates/book/book_create.html
{% extends 'base.html' %}

{% block title %}書籍登録{% endblock %}

{% block content %}
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit", value="登録する">
    </form>
    
{% endblock %}

09_Django/project3/bookproject/book/templates/book/book_delete.html
{% extends 'base.html' %}

{% block title %}書籍削除{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <button type="submit">{{ object.title }}を削除する</button>
    </form>
{% endblock %}

09_Django/project3/bookproject/book/templates/book/book_detail.html
{% extends 'base.html' %}

{% block title %}{{ object.title }}{% endblock %}
{% block h1 %}書籍詳細{% endblock %}

{% block content %}

    <div class="p-4 m-4 bg-light border border-success rounded">
        <h2 class="text-succes">{{ object.title }}</h2>
        <p>{{ object.text }}</p>
        <a href="{% url 'list-book' %}" class="btn btn-primary">一覧へ</a>
        <a href="{% url 'update-book' object.pk %}" class="btn btn-primary">編集する</a>
        <a href="{% url 'delete-book' object.pk %}" class="btn btn-primary">削除する</a>
        <h6 class="card-title">{{ object.category }}</h6>
        
    </div>

{% endblock content %}

09_Django/project3/bookproject/book/templates/book/book_list.html
{% extends 'base.html' %}

{% block title %}書籍一覧{% endblock %}
{% block h1 %}書籍一覧{% endblock %}

{% block content %}

    {% for item in object_list %}

    <div class="p-4 m-4 bg-light border border-success rounded">
        <h2 class="text-succes">{{ item.title }}</h2>
        <h6>カテゴリ：{{ item.category }}</h6>
        <div class="mt-3">
            <a href="{% url 'detail-book' item.pk %}">詳細</a>
        </div>
    </div>

    {% endfor %}
{% endblock content %}

09_Django/project3/bookproject/book/templates/book/book_update.html
{% extends 'base.html' %}

{% block title %}書籍更新{% endblock %}

{% block content %}
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">更新する</button>
    </form>
    
{% endblock %}

09_Django/project3/bookproject/book/templates/book/index.html
{% extends 'base.html' %}
{% block title %}書籍一覧{% endblock %}
{% block h1 %}書籍一覧{% endblock %}

{% block content %}
    {% for item in object_list %}
        <div class="p-4 m-4 bg-light border border-success rounded">
            <h2 class="text-success">{{ item.title }}</h2>
            <h6>カテゴリー：{{ item.category }}</h6>
            <div class="mt-3">
                <a href="{% url 'detail-book' item.pk %}">詳細</a>
            </div>
        </div>
    {% endfor %}
{% endblock  %}

09_Django/project3/bookproject/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <!-- bootstrap -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
        <title>{% block title%}{%endblock title %} | 独ソアプリ</title>
    </head>
    <body>
        <nav class="navbar navbar-dark bg-success sticky-top">
            <div class="navbar-nav d-flex flex-row">
                <a class="navbar-brand mx-3" href="{% url 'list-book' %}">一覧</a>
                <a class="navbar-brand mx-3" href="{% url 'create-book' %}">登録</a>
            </div>
            <div class="navbar-nav d-flex flex-row">
                {% if request.user.is_authenticated %}
                    <a href="{% url 'accounts:logout' %}" class="nav-link mx-3">Logout</a>
                {% else %}
                    <a href="{% url 'accounts:login' %}" class="nav-link mx-3">Login</a>
                    <a href="{% url 'accounts:signup' %}" class="nav-link mx-3">Signup</a>
                {% endif %}
            </div>
        </nav>
        <div class="p-4">
            <h1>{% block h1 %}{% endblock %}</h1>
            {% block content %}{% endblock content %}
        </div>
    </body>
</html>